### PR TITLE
fix: snap scale

### LINKED ISSUE #673: Limit minimum scale
Should be higher than 0 to prevent the asset from flipping or disappearing

### LINKED ISSUE #725: Scaling an item to zero makes it unselectable

### PR DESCRIPTION
**Pull request by belohlavek**
Closes #725 
Closes #673

### CODE REVIEW

File: src/modules/editor/utils.ts [hunk 1]
```diff
@@ -81,3 +82,11 @@ export function resizeScreenshot(screenshot: string, maxWidth: number, maxHeight
     img.src = screenshot
   })
 }
+
+export function snapScale(scale: Vector3): Vector3 {
+  return {
+    x: scale.x === 0 ? 0.001 : scale.x,
+    y: scale.y === 0 ? 0.001 : scale.y,
+    z: scale.z === 0 ? 0.001 : scale.z
```
Comment (nicosantangelo) [inline src/modules/editor/utils.ts]: Question, maybe it'd be safer to do this?

```ts
  const threshold = 0.001
  return {
    x: scale.x < threshold ? threshold : scale.x,
    y: scale.y < threshold ? threshold : scale.y,
    z: scale.z < threshold ? threshold : scale.z
  }
```
