### PR TITLE
fix: renameEntity and removeEntityReferences

### LINKED ISSUE #839: Cloudsaves indicator shouldn't have a cursor pointer since it's not clickable
Cloudsaves indicator shouldn't have a cursor pointer since it's not clickable

### PR DESCRIPTION
**Pull request by belohlavek**
Closes #839 

And makes it so that entity fields are also affected by renameEntity/removeEntityReferences

### CODE REVIEW

File: src/modules/scene/utils.ts [hunk 1]
```diff
@@ -217,20 +217,26 @@ export function getDefaultValues(entityName: string, parameters: AssetParameter[
  * Swaps all references to `oldName` for `newName` inside a script's actions.
  *
  * Mutates the object.
+ *
+ * @param paraneters The Asset parameters
```
Comment (cazala) [inline src/modules/scene/utils.ts]: paraNeters
