### PR TITLE
fix: Publish wizard UI issues

### LINKED ISSUE #2393: [Publish Wizard] Fix UI issues
## 🎉 Description

Fix UI issues found in the last release. 

Tasks:
- [x] In the `ConfirmCollectionItems Step`, add "price" to the list of things that can be modified.
- [x] In the `ConfirmCollectionItems Step`, add "later" at the end of the description text (after modified). So it will end "can be modified later".
- [x] Wrap the item's name when it is too long to avoid brakes the bodytype badge.
- [x] Avoid closing the modal when the user clicks outside of it, only when the user clicks on the close button.
- [x] Add a Back button in the steps: `ConfirmCollectionItems`, `ReviewContentPolicy` and `PayPublicationFee`.
- [x] In the `ConfirmCollectionName Step`, should put the focus on the input they need to complete and make the input label white (instead of gray).
- [x] The color used for showing active and completed steps in the progress indicator should be the primary color.
- [x] The "Forum post" button in the `Congratulations Step` should open a new window to see the forum.
- [x] Add the button "FINISH" in the `Congratulations Step`

### PR DESCRIPTION
**Pull request by cyaiox**
This PR fixes some UI issues in the new publish wizard collection flow and adds UI improvements.

Closes #2393

### CODE REVIEW

File: src/lib/validators.ts [hunk 1]
```diff
@@ -1 +1 @@
-export const emailRegex = /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/
+export const emailRegex = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
```
Comment (cyaiox) [inline src/lib/validators.ts:1]: Updated this email regex to match the email addresses correctly: `example@domain.some`

**Review by juanmahidalgo — APPROVED** [review]
LGTM! Not sure if it was ready to review but since it was asked I did 😂
