### PR TITLE
fix: ground entity names

### LINKED ISSUE #882: Ground deployment failure on multipleparcel scenes

### PR DESCRIPTION
**Pull request by belohlavek**
Properly generate ground entity names (entity{N})
Get unique names from assets rather than GLTFShapes (fixes case where there's an scene.gltf model that conflicts with the scene entity wrapper on export)
Keep old naming system for legacy purposes/migration

Closes #882

### CODE REVIEW

File: src/modules/scene/utils.ts [hunk 1]
```diff
@@ -127,17 +127,20 @@ export function getEntityName(scene: Scene, entityComponents: EntityDefinition['
...
   let attempts = 1
   let rawName = 'entity'
 
   for (let component of components) {
     try {
       if (component.type === ComponentType.GLTFShape) {
-        rawName = getGLTFShapeName(component as ComponentDefinition<ComponentType.GLTFShape>)
+        const asset = assets[(component as ComponentDefinition<ComponentType.GLTFShape>).data.assetId]
+        if (asset) {
+          rawName = asset.name
```
Comment (cazala) [inline src/modules/scene/utils.ts]: this should be sanitized, and preferably camelcased too
