### PR TITLE
fix: Disable claim name confirm button when loading

### LINKED ISSUE #1532: Disable the claim confirm button when claiming a name and it is loading

### PR DESCRIPTION
**Pull request by fzavalia**
Closes #1532 

Sep-02-2021 12-11-55

Also fixes text in spanish on the ClaimNameFatFingerModal that was not being correctly replaced.

Screen Shot 2021-09-02 at 12 08 42

### CODE REVIEW

File: src/components/Modals/ClaimNameFatFingerModal/ClaimNameFatFingerModal.tsx [hunk 1]
```diff
@@ -53,7 +53,7 @@ export default class ClaimNameFatFingerModal extends React.PureComponent<Props,
             <Button secondary onClick={this.handleClose} type="button">
               {t('global.cancel')}
             </Button>
-            <Button primary type="submit" disabled={areNamesDifferent} loading={isLoading}>
+            <Button primary type="submit" disabled={areNamesDifferent || isLoading} loading={isLoading}>
```
Comment (fzavalia) [inline src/components/Modals/ClaimNameFatFingerModal/ClaimNameFatFingerModal.tsx:56]: Maybe the button should be implicitly disabled when the loading prop is true

Comment (LautaroPetaccio) [reply src/components/Modals/ClaimNameFatFingerModal/ClaimNameFatFingerModal.tsx:56]: That is not a bad idea at all, but we're using this button (that comes from semantic-react-ui) everywhere and we are going to be introducing a breaking change.

**Review by LautaroPetaccio — APPROVED** [review]
