### PR TITLE
fix: vertical snap to bounds

### LINKED ISSUE #412: Vertically out of bounds objets are not clamped

### PR DESCRIPTION
**Pull request by belohlavek**
Closes #412

### CODE REVIEW

File: src/modules/scene/sagas.ts [hunk 1]
```diff
@@ -280,3 +282,24 @@ function* handleSetGround(action: SetGroundAction) {
...
+
+function* handleFixCurrentScene() {
+  const scene: Scene = yield select(getCurrentScene)
+  const bounds: ReturnType<typeof getCurrentBounds> = yield select(getCurrentBounds)
+  const componentIdKeys = Object.keys(scene.components)
+  let components = { ...scene.components }
+
+  for (let key of componentIdKeys) {
+    const component = scene.components[key] as ComponentDefinition<ComponentType.Transform>
+    if (component.type === ComponentType.Transform && bounds) {
```
Comment (cazala) [inline src/modules/scene/sagas.ts]: instead of adding the `&& bounds` here, we could add an `if (!bounds) return` before the for loop
