### PR TITLE
fix: Copy button in Share Modal

### LINKED ISSUE #1483: Copy a scene doesnt work
The copy button does nothing, marking, right-click, copy with mouse does nothing... And ctrl+c doesnt copy the URL either..

### PR DESCRIPTION
**Pull request by LautaroPetaccio**
This PR fixes the copy button by using the `CopyToClipboard` component. It also adds a simple border to the button so it doesn't merge with the input next to it.
copy-share

Closes #1483

### CODE REVIEW

File: src/components/Modals/ShareModal/ShareModal.tsx [hunk 1]
```diff
@@ -46,19 +48,11 @@ export default class ShareModal extends React.PureComponent<Props, State> {
...
-      if (selection) {
-        selection.removeAllRanges()
-        input.blur()
-        this.setState({ copied: true })
-      }
-      this.props.onShare(ShareTarget.LINK)
+  handleCopyLink = () => {
+    const { copiedTimer } = this.state
+    if (copiedTimer === undefined) {
+      const newCopiedTimer = setTimeout(() => this.setState({ copied: false, copiedTimer: undefined }), 2000)
```
Comment (cazala) [inline src/components/Modals/ShareModal/ShareModal.tsx:54]: We should check the component is still mounted by the time the `setTimeout` is executed, otherwise the `this.setState` will complain. We can do that by setting a flag at the instance level when the component mounts (and unsetting it when it unmounts) and checking against it within the `setTimeout` callback.

**Review by cazala — CHANGES_REQUESTED** [review]

**Review by cazala — APPROVED** [review]
