### PR TITLE
fix: Upload video step styles

### LINKED ISSUE #2753: [CreateSingleItemModal] Await until finish loading and processing the model file before moving to the "Upload Video Step"

### LINKED ISSUE #2754: [UploadVideoStep] Change the styles of the modal that allows users to upload the showcase video of a smart wearable

### PR DESCRIPTION
**Pull request by kevinszuchet**
Closes #2753
Closes #2754

https://www.loom.com/share/04c73575d6434b3bbc7e39132462f79e?sid=6ae01e1b-ac6f-43ab-a88d-4f737acc0db5

### CODE REVIEW

**Review by cyaiox — APPROVED** [review]

File: src/components/ItemImport/ItemImport.tsx [hunk 1]
```diff
@@ -3,20 +3,46 @@ import { t, T } from 'decentraland-dapps/dist/modules/translation/utils'
 import { Loader } from 'decentraland-ui'
 import FileImport from 'components/FileImport'
 import { InfoIcon } from 'components/InfoIcon'
-import { Props } from './ItemImport.types'
+import { Props, State } from './ItemImport.types'
 import styles from './ItemImport.module.css'
+import { ITEM_LOADED_CHECK_DELAY } from 'components/Modals/CreateSingleItemModal/constants'
```
Comment (cyaiox) [inline src/components/ItemImport/ItemImport.tsx:8]: could you please move this import above?
