### PR TITLE
fix: restore gizmos after exiting preview mode

### LINKED ISSUE #196: Preview breaks gizmos
- Enter into preview mode

- Exit preview mode

- Gizmos don't work anymore on already placed models (new models added after this come with gizmos)

### PR DESCRIPTION
**Pull request by cazala**
Closes #196

### CODE REVIEW

**Comment by belohlavek** [comment]
Shouldn't this be #196 ?

File: src/ecsScene/scene.ts [hunk 1]
```diff
@@ -50,7 +50,7 @@ function handleExternalAction(message: { type: string; payload: Record<string, a
           entity.remove(Gizmos)
         } else {
           const staticEntities = engine.getComponentGroup(StaticEntity)
-          if (!staticEntities.hasEntity(entity.uuid)) {
+          if (!staticEntities.hasEntity(entity)) {
```
Comment (nicosantangelo) [inline src/ecsScene/scene.ts]: _Question_: Should this be here? I think it's a change on `decentraland-ecs`? but I don't see an update

Comment (belohlavek) [reply src/ecsScene/scene.ts]: There is an update but my branch has the latest one, Juanca updated but removed the updated version so we can use mine. I think we should revert this.
