### PR TITLE
fix: publish to LAND while logged out

### LINKED ISSUE #614: Publish to LAND doesn't work when logged out
Publish to LAND doesn't work when logged out because it's hitting some endpoints (`GET /deployments` and `POST /media`) that shouldn't hit while logged out.

### PR DESCRIPTION
**Pull request by cazala**
Fixes #614

### CODE REVIEW

File: src/components/Modals/DeployModal/DeployToLand/LandAtlas/LandAtlas.tsx [hunk 1]
```diff
@@ -25,8 +25,10 @@ export default class LandAtlas extends React.PureComponent<Props, State> {
 
   componentDidMount() {
     this.mounted = true
-    const { onFetchDeployments } = this.props
-    onFetchDeployments()
+    const { isLoggedIn, onFetchDeployments } = this.props
+    if (isLoggedIn) {
+      onFetchDeployments()
```
Comment (belohlavek) [inline src/components/Modals/DeployModal/DeployToLand/LandAtlas/LandAtlas.tsx]: this now only happens when logged in?

Comment (cazala) [reply src/components/Modals/DeployModal/DeployToLand/LandAtlas/LandAtlas.tsx]: yes, if you are not logged in, you aready have your deployments in memory

Comment (cazala) [reply src/components/Modals/DeployModal/DeployToLand/LandAtlas/LandAtlas.tsx]: they come as `occupiedParcels`
