### PR TITLE
fix: Error when the curator has no profile data

### LINKED ISSUE #2013: [BUG] Error when the curator has no name associated
When accessing the edit curator modal, if the curator has no name associated, it throws an error and the modal is not opened.

### PR DESCRIPTION
**Pull request by juanmahidalgo**
Closes #2013

### CODE REVIEW

File: src/modules/curations/collectionCuration/utils.ts [hunk 1]
```diff
@@ -15,9 +15,10 @@ export const getCollectionCurationState = (collection: Collection, curation: Col
       return CurationStatus.DISABLED
     } else if (curation && curation.status === 'rejected') {
       return CurationStatus.REJECTED
-    } else if (curation && curation.status === 'pending' && curation.assignee) {
-      return CurationStatus.UNDER_REVIEW
     }
   }
+  if (curation && curation.status === 'pending' && curation.assignee) {
```
Comment (juanmahidalgo) [inline src/modules/curations/collectionCuration/utils.ts:20]: some collections that have `isApproved` as `true` (because they are in the catalyst) but they have a curation in pending and an assignee were listed as `to review` but they should be listed as `under_review`

File: src/components/Modals/EditCurationAssigneeModal/EditCurationAssigneeModal.tsx [hunk 2]
```diff
@@ -62,7 +62,7 @@ export default class EditCurationAssigneeModal extends React.PureComponent<Props
                     value === UNASSIGN_PLACEHOLDER
                       ? `- ${t('curation_page.assign_modal.unassign')} -`
                       : value === address
-                      ? `${profiles[address].avatars[0].name} (${t('collection_row.you')})`
+                      ? `${profiles[address]?.avatars[0].name} (${t('collection_row.you')})`
```
Comment (fzavalia) [inline src/components/Modals/EditCurationAssigneeModal/EditCurationAssigneeModal.tsx:65]: If the profile for the given address does not exist,  (${t('collection_row.you')}) will have an empty space in the beginning, is this intentional?

Comment (juanmahidalgo) [reply src/components/Modals/EditCurationAssigneeModal/EditCurationAssigneeModal.tsx]: Oh yeah, good catch. Instead of that, I just added to show the address and the `(you)` text.

**Review by fzavalia — APPROVED** [review]
