### PR TITLE
fix: edit urn modal

### LINKED ISSUE #1661: Add the Edit URN Modal
Add a modal that can edit both a TP Collection or an Item URN. We could create a generic EditThirdPartyURN and let it decide which URN is being edited using the resource supplied. It should be opened from the Edit URN context menus (already present in the code as `onOpenModal('BuySlotModal', {})`)

### PR DESCRIPTION
**Pull request by nicosantangelo**
https://user-images.githubusercontent.com/692077/141846644-5b7702d2-3c6b-4f12-98aa-40e4934fe36e.mov

Closes #1661

### CODE REVIEW

File: src/modules/collection/sagas.ts [hunk 1]
```diff
@@ -134,7 +135,6 @@ export function* collectionSaga(builder: BuilderAPI, catalyst: CatalystClient) {
     try {
       const collections: Collection[] = yield call(() => builder.fetchCollections(address))
       yield put(fetchCollectionsSuccess(collections))
-      yield put(closeModal('CreateCollectionModal'))
```
Comment (LautaroPetaccio) [inline src/modules/collection/sagas.ts:137]: Was this modal mistakenly closed before? Because the `handleSaveCollectionSuccess` only handles the actions of saving collections.

**Review by LautaroPetaccio — CHANGES_REQUESTED** [review]

File: src/components/Modals/EditURNModal/EditURNModal.tsx [hunk 2]
```diff
@@ -0,0 +1,95 @@
...
+import { buildThirdPartyURN, DecodedURN, decodeURN, URNType } from 'lib/urn'
+import { Item } from 'modules/item/types'
+import { Collection } from 'modules/collection/types'
+import { Props, State, EditURNModalMetadata } from './EditURNModal.types'
+
+export default class EditURNModal extends React.PureComponent<Props, State> {
+  decodedURN: DecodedURN<URNType.COLLECTIONS_THIRDPARTY> = this.decodeURN()
+
+  state: State = {
+    newURNSection: ''
```
[the remark this answers is not in the document]
Comment (nicosantangelo) [reply src/components/Modals/EditURNModal/EditURNModal.tsx:14]: I couldn't figure out a better name for this property, but yes!. It holds either the `collection-id` or the `token-id`, depending on the URN (the last part of the URN)

File: src/modules/collection/sagas.ts (hunk 1 above)
Comment (nicosantangelo) [reply src/modules/collection/sagas.ts:137]: I think so, I checked the commit that added it and didn't seem to make sense:
[`fix: Fix BuilderAPI cyclic dependency`](https://github.com/decentraland/builder/commit/9073f52eff63452731431bd7724a854a30c4fb28)

**Review by LautaroPetaccio — APPROVED** [review]
