### PR TITLE
fix: setting ground

### LINKED ISSUE #707: Deleting every asset on my asset pack resets the name when trying to add more
[asset-pack-name-gone.mov.zip](https://github.com/decentraland/builder/files/3644175/asset-pack-name-gone.mov.zip)

### LINKED ISSUE #709: Editing an asset and setting the ground explodes
[broken-edit.mov.zip](https://github.com/decentraland/builder/files/3644200/broken-edit.mov.zip)

### PR DESCRIPTION
**Pull request by belohlavek**
Closes #709 
Closes #707

### CODE REVIEW

File: src/components/AssetsEditor/SingleAssetEditor/SingleAssetEditor.tsx [hunk 1]
```diff
@@ -67,8 +66,9 @@ export default class SingleAssetEditor<T extends RawAsset | Asset> extends React
     const { asset } = this.props
 
     let mappings: Asset['contents'] | RawAsset['contents']
+    const contentValues = Object.values(asset.contents)
 
-    if (!isRemoteURL(asset.thumbnail)) {
+    if (typeof contentValues[0] !== 'string') {
       mappings = rawMappingsToObjectURL((asset as RawAsset).contents)
     } else {
       mappings = Object.keys((asset as Asset).contents).reduce<Asset['contents']>((acc, path) => {
```
Comment (nicosantangelo) [inline src/components/AssetsEditor/SingleAssetEditor/SingleAssetEditor.tsx]: I know it's not related to this PR, but there's a `as any` below this line that I think it's not necessary

File: src/components/AssetsEditor/SingleAssetEditor/SingleAssetEditor.tsx [hunk 2]
```diff
@@ -67,8 +66,9 @@ export default class SingleAssetEditor<T extends RawAsset | Asset> extends React
     const { asset } = this.props
 
     let mappings: Asset['contents'] | RawAsset['contents']
+    const contentValues = Object.values(asset.contents)
 
-    if (!isRemoteURL(asset.thumbnail)) {
+    if (typeof contentValues[0] !== 'string') {
```
Comment (nicosantangelo) [inline src/components/AssetsEditor/SingleAssetEditor/SingleAssetEditor.tsx]: I'm not qualified to attest if this is right or wrong but when I click the checkbox twice I get:

image

cc: @cazala

Comment (belohlavek) [reply src/components/AssetsEditor/SingleAssetEditor/SingleAssetEditor.tsx]: oldy file
