### PR TITLE
fix: thumbnails for duplicated scenes

### LINKED ISSUE #613: Duplicated scene has no thumbnail
Repro:

While logged in and in dashboard:
- Duplicate a scene (it will have a thumbnail)
- Refresh the page (thumbnail is gone)

### PR DESCRIPTION
**Pull request by belohlavek**
Add thumbnail to the duplicated project

If the image is referenced remotely, fetch it and convert it to base64

On project save success the new media should be saved separately

Closes #613

### CODE REVIEW

File: src/modules/project/sagas.ts [hunk 1]
```diff
@@ -116,8 +116,14 @@ function* handleDuplicateProject(action: DuplicateProjectAction) {
 
   const scene = yield getSceneByProjectId(project.id)
 
+  let thumbnail = project.thumbnail
+
+  if (thumbnail && !thumbnail.startsWith('data:image/png;')) {
```
Comment (cazala) [inline src/modules/project/sagas.ts]: should we use `startsWith('http')` to keep it consitent? (https://github.com/decentraland/builder/blob/master/src/components/ProjectCard/ProjectCard.tsx#L72) 

Also if we are going to `fetch` it should be an http/s endpoint

Comment (belohlavek) [reply src/modules/project/sagas.ts]: doh, yep
