### PR TITLE
fix: Allow publishing world when only owning ens names

### LINKED ISSUE #2907: Allow user to publish world when they have no DCL Names but yes another ENS names
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcGJjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c32bc1ca899440271f7722bb50ce9cc905326431/image.png)

### PR DESCRIPTION
**Pull request by fzavalia**
Closes #2907

### CODE REVIEW

File: src/components/Modals/DeployModal/DeployToWorld_WorldsForEnsOwnersFeature/DeployToWorld.tsx [hunk 1]
```diff
@@ -355,19 +355,7 @@ export default function DeployToWorld({
       <>
         <div className={styles.modalHeader}>
           <h3>{t('deployment_modal.deploy_world.title')}</h3>
-          <span>
-            {t('deployment_modal.deploy_world.description')}
-            <Popup
```
Comment (fzavalia) [inline src/components/Modals/DeployModal/DeployToWorld_WorldsForEnsOwnersFeature/DeployToWorld.tsx:360]: Removed the popup as there is no info to add

**Review by LautaroPetaccio — APPROVED** [review]
